name = "free-proxy"
main = "build/index.js"
compatibility_date = "2026-08-08"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[dev]
port = 80

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
